#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  redLed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  yellowLed,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  greenLed,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  liftLim,        sensorTouch)
#pragma config(Sensor, dgtl12, testLed,        sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  flyEnc,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  liftEnc,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  rWheelEnc,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  lWheelEnc,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           frWheel,       tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           brWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port3,           blWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port4,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           lift,          tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           trFly,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           brFly,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           blFly,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           tlFly,         tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          flWheel,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#define RKCOMP_LCD //Enable LCD stuff in rkCompetition

#include "rkCompetition002.h"
#include "rkUtil002.h"
#include "rkControl/base002.h"
#include "rkControl/diff001.h"
#include "rkControl/tbh004.h"
#include "rkControl/tbhController002.h"

float flyLRPwr = 800, flySRPwr = 500;
const float autonFlyPwr = 800;
Tbh flyTbh, liftTbh;
ADiff flyDiff, fly2Diff, liftDiff;
TbhController flyCtl, liftCtl;

const float velThresh = 50,
	accelThresh = 200;

void lcdDispPwr(bool doUseLRPwr) {
	if (doUseLRPwr) {
		displayLCDCenteredString(0, "Long  Power:");
		displayLCDNumber(1, 0, flyLRPwr);
	}
	else {
		displayLCDCenteredString(0, "Short Power:");
		displayLCDNumber(1, 0, flySRPwr);
	}
}

task lcd() {
	string str;
	float pwrBtns;
	const TTimers lcdTimer = T3;
	const float flyPwrIncrement = 10;
	bool doUseLRPwr = true;

	while (true) {
		bLcdBacklight = !bIfiRobotDisabled

		if (nLCDButtons & kButtonCenter) {
			sprintf(str, "%6.2f // %-6.2f", nImmediateBatteryLevel / 1000., BackupBatteryLevel / 1000.);

			clearLCD();
			displayLCDCenteredString(0, "Battery:");
			displayLCDString(1, 0, str);
		}
		else if (bIfiRobotDisabled) {
			clearLCD();

			displayLCDCenteredString(0, "Moosebot Mk. II");
			displayLCDCenteredString(1, "4800Buckets");
		}
		else if (bIfiAutonomousMode) {
		}
		else {
			if (vexRT[Btn7L] ^ vexRT[Btn7R])
				doUseLRPwr = vexRT[Btn7L];

			clearLCD();

			if (time1[lcdTimer] < 2000 || vexRT[Btn7L] || vexRT[Btn7R]) lcdDispPwr(doUseLRPwr);
			else {
				if (flyTbh.doRun) {
					sprintf(str, "% 07.2f  % 07.2f",
						fmaxf(-999.99, fminf(999.99, flyDiff.out)),
						fmaxf(-999.99, fminf(999.99, flyTbh.err)));
					displayLCDString(0, 0, str);

					sprintf(str, "% 07.2f  % 07.2f",
						fmaxf(-999.99, fminf(999.99, fly2Diff.out)),
						fmaxf(-999.99, fminf(999.99, flyTbh.out)));
					displayLCDString(1, 0, str);
				}
				else {
					sprintf(str, "%-8s%8s", "Speed", "Error");
					displayLCDString(0, 0, str);

					sprintf(str, "%-8s%8s", "Accel", "Out");
					displayLCDString(1, 0, str);
				}
			}

			pwrBtns = twoWay((nLCDButtons & kButtonLeft) || vexRT[Btn7D], -flyPwrIncrement, (nLCDButtons & kButtonRight) || vexRT[Btn7U], flyPwrIncrement);

			if (pwrBtns != 0) {
				if (doUseLRPwr) flyLRPwr = fmaxf(0, flyLRPwr + pwrBtns);
				else flySRPwr = fmaxf(0, flySRPwr + pwrBtns);

				clearLCD();
				lcdDispPwr(doUseLRPwr);

				clearTimer(lcdTimer);
				while(((nLCDButtons & (kButtonLeft | kButtonRight)) || vexRT[Btn7D] || vexRT[Btn7U]) && time1[lcdTimer] < 300) { wait1Msec(25); EndTimeSlice(); }

				do {
					pwrBtns = twoWay((nLCDButtons & kButtonLeft) || vexRT[Btn7D], -flyPwrIncrement, (nLCDButtons & kButtonRight) || vexRT[Btn7U], flyPwrIncrement);

					if (doUseLRPwr) flyLRPwr = fmaxf(0, flyLRPwr + pwrBtns);
					else flySRPwr = fmaxf(0, flySRPwr + pwrBtns);

					clearLCD();
					lcdDispPwr(doUseLRPwr);

					wait1Msec(100);
					EndTimeSlice();
				} while(pwrBtns != 0);

				clearTimer(lcdTimer);
			}
		}

		SensorValue[redLed] =
			SensorValue[yellowLed] =
			SensorValue[greenLed] = 0;

		if (!bIfiRobotDisabled) {
			if (flyTbh.doRun) {
				if (isTbhInThresh(&flyTbh, velThresh)) {
					if (abs(fly2Diff.out) <= accelThresh) SensorValue[greenLed] = 1;
					else  SensorValue[yellowLed] = 1;
				}
				else SensorValue[redLed] = 1;
			}

			SensorValue[testLed] = SensorValue[liftLim];
		}
		else SensorValue[testLed] = 0;

		wait1Msec(100);
	}
}

void startFlyTbh(bool useCtl) {
	resetTbh(&flyTbh, 0);

	resetADiff(&flyDiff, 0);
	resetADiff(&fly2Diff, 0);

	if (useCtl) updateTbhController(&flyCtl, 0);
	else setTbhDoRun(&flyTbh, true);

	SensorValue[flyEnc] = 0;
}

void startLiftTbh(bool useCtl) {
  resetTbh(&liftTbh, 0);

  resetADiff(&liftDiff, 0);

  if (useCtl) updateTbhController(&liftCtl, 0);
  else setTbhDoRun(&liftTbh, true);

  SensorValue[liftEnc] = 0;
}

void stopCtls() {
	setTbhDoRun(&flyTbh, false);
	setTbhDoRun(&liftTbh, false);

	stopCtlLoop();
}

void init() {
	bLCDBacklight = true;
	clearLCD();

  ctlLoopInterval = 50;

  initTbh(&flyTbh, 5, .25, 127, true);
  initTbh(&liftTbh, 10, .5, 127, false);

  initTbhController(&flyCtl, &flyTbh, false);
  initTbhController(&liftCtl, &liftTbh, false);
}

void updateCtl(float dt) {
	updateADiff(&flyDiff, SensorValue[flyEnc], dt);
	updateADiff(&fly2Diff, flyDiff.out, dt);
	updateADiff(&liftDiff, SensorValue[liftEnc], dt);

	if (flyTbh.doUpdate)
		motor[blFly] = motor[tlFly] =
			motor[brFly] = motor[trFly] = updateTbh(&flyTbh, flyDiff.out, dt);

	if (liftTbh.doUpdate)
		motor[lift] = updateTbh(&liftTbh, -liftDiff.out, dt);
}

task auton() {
	const float recoilThresh = 75;

	startFlyTbh(false);
	startCtlLoop();

	setTbh(&flyTbh, autonFlyPwr);

	block(!isTbhInThresh(&flyTbh, velThresh) || abs(fly2Diff.out) > accelThresh);

	motor[lift] = 127;
	motor[intake] = 127;

	wait1Msec(600);

	while (true) {
		motor[intake] = motor[lift] = 80;

		block(isTbhInThresh(&flyTbh, recoilThresh) && abs(fly2Diff.out) <= accelThresh);

		motor[intake] = motor[lift] = 0;

		block(!isTbhInThresh(&flyTbh, velThresh) || abs(fly2Diff.out) > accelThresh);
	}
}

void endAuton() {
	stopCtls();
}

task userOp() {
	startFlyTbh(true);
	startCtlLoop();

	const float cutFac = 3;
	bool cutDrive = false,
		flipDrive = false,
		doTank = false;

	word driveX, driveY,
		cutBtn = 0, lastCutBtn = 0,
		flipBtn = 0, lastFlipBtn = 0,
		flyFwdBtn = 0, lastFlyFwdBtn = 0,
		flyBackBtn = 0, lastFlyBackBtn = 0,
		flyDir = 0;

	while (true) {
		driveX = vexRT[ChRX];
		driveY = vexRT[ChLY];

		cutBtn = vexRT[Btn8U];
		flipBtn = vexRT[Btn8D];

		if (cutBtn && !lastCutBtn)
			cutDrive = !cutDrive;

		if (flipBtn && !lastFlipBtn)
			flipDrive = !flipDrive;

		lastCutBtn = cutBtn;
		lastFlipBtn = flipBtn;

		if (cutDrive) {
			driveX = (word)(driveX / cutFac);
			driveY = (word)(driveY / cutFac);
		}

		if (flipDrive) driveY *= -1;

		arcade4(driveX, driveY, flWheel, blWheel, frWheel, brWheel);

		lastFlyFwdBtn = flyFwdBtn;
		lastFlyBackBtn = flyBackBtn;

		flyFwdBtn = vexRT[Btn5U];
		flyBackBtn = vexRT[Btn5D];

		if (flyFwdBtn && !lastFlyFwdBtn)
			flyDir = flyDir == 1 ? 0 : 1;

		if (flyBackBtn && !lastFlyBackBtn)
			flyDir = flyDir == 2 ? 0 : 2;

		switch (flyDir) {
			case 1: updateTbhController(&flyCtl, flyLRPwr); break;
			case 2: updateTbhController(&flyCtl, flySRPwr); break;
			default: updateTbhController(&flyCtl, 0); break;
		}

		motor[intake] = motor[lift] =
			joyDigi2(Btn6U, 127, Btn6D, -127);

		EndTimeSlice();
	}
}

void endUserOp() {
	stopCtls();
}
